config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    collection do
      post :search
    end
  end
  resources :user_search
  devise_for :users

  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    include PgSearch::Model

    validates :title, presence: true, uniqueness: true, length: { maximum: 150 }
    validates :body, presence: true, length: { maximum: 2500 }

    scope :sorted, ->{ order(created_at: :asc) }

    pg_search_scope :article_search,
                    against: [:title],
                    using: { tsearch: { prefix: true } }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_searches, dependent: :destroy

  validates :username, :email, presence: true, length: { maximum: 250 }
  validate :password_requirements_are_met, on: :create

  def recent_searches
    user_searches.order(created_at: :desc).limit(5)
  end

  def trending_articles
    user_searches.select(:title).group(:title).having("count(*) > 1").size
  end

  def password_requirements_are_met
    rules = {
      " must contain at least one lowercase letter"  => /[a-z]+/,
      " must contain at least one uppercase letter"  => /[A-Z]+/,
      " must contain at least one digit"             => /\d+/,
      " must contain at least one special character" => /[^A-Za-z0-9]+/
    }
  
    rules.each do |message, regex|
      errors.add( :password, message ) unless password.match( regex )
    end
  end
end

app/models/user_search.rb
class UserSearch < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 150 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    protect_from_forgery prepend: true
    before_action :update_allowed_parameters, if: :devise_controller?

    private

    def update_allowed_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password) }
        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :current_password) }
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end

    def search
        if params[:query].present?
            @search_results = Article.article_search(params[:query])
            @search_results.each do |article|
                save_results(article.title)
            end
        else
            @search_results = []
        end
        respond_to do |format|
            format.turbo_stream do
                render turbo_stream: turbo_stream.update("search_results",
                    partial: "articles/search_results", locals: { articles: @search_results })
            end
        end
    end

    def save_results(data)
        results = UserSearch.new(title: data, user_id: current_user.id)
        results.save!
    end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => error
        if get?
          raise error
        elsif has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          redirect_to navigation_location
        end
      end
    end
  
    self.responder = Responder
    respond_to :html, :turbo_stream
end

app/controllers/user_search_controller.rb
class UserSearchController < ApplicationController
  def index
    @results = User.all.includes(:user_searches)
  end

  def show
    @search_result = UserSearch.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/user_search_helper.rb
module UserSearchHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <%= link_to article_path(article), class: "text-decoration-none" do%>
    <p>
      <%= article.title %>
    </p>
    <p class='text-dark'><%= truncate(article.body, :length => 170, :separator => ' ') %></p>
    <footer class="blockquote-footer text-end"><cite title="Source Title">Posted <%= time_ago_in_words(article.created_at)%> ago</cite></footer>
    <% end %>
</div>

app/views/articles/_articles.html.erb
<%= turbo_frame_tag "articles" do %>
  <%= render articles %>
<% end %>

app/views/articles/_search_form.html.erb
<div id="form">
    <%= form_with(url: search_articles_path, method: :post, data: {controller: "search-form", turbo_frame: "articles", turbo_action: "advance"}, class: "form-outline mb-4") do |form| %>
        <%= form.label :query, "Search by title:", class: "form-label" %>
        <%= form.text_field :query, class: "form-control", data: {action: "input->search-form#search"} %>
    <% end %>

    <div id="search_results"></div>    
</div>

app/views/articles/_search_results.html.erb
<% if articles.present? %>
  <div class="card w-full bg-blue-50 mb-5 p-3">
    <p>Found <%= articles.count %> items</p>
    <% articles.each do |article| %>
      <br>
      <%= link_to highlight(article.title, params[:title_search]), article, class: "pt-3" %>
    <% end %>
  </div>
<% end %>

app/views/articles/index.html.erb
<section class="container m-5">
    <%= render "articles/search_form" %>
    <div class="card w-full p-3 mb-5">
        <div class="card-body">
            <h5 class="card-title text-center">Articles</h5>
            <%= render "articles", articles: @articles %>
        </div> 
    </div>
</section>

app/views/articles/show.html.erb
<div class="container">
    <h3 class="text-bold pb-3"><%= @article.title %></h3>
    <p> <%= @article.body %></p>
    <%= link_to "Back to articles", articles_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchEngine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" 
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" 
      integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
  </head>

  <body>
      <% if notice %>
        <p class="alert alert-success text-center"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger text-center"><%= alert %></p>
      <% end %>
    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="nav-link">
            <%= link_to 'Articles', articles_path, class: "navbar-brand" %>
          </div>
          <div class="nav-link">
            <%= link_to 'Analitics', user_search_index_path, class: "navbar-brand" %>
          </div>
      </nav>
    </div>
    <%= yield %>
  </body>
</html>

app/views/user_search/index.html.erb
<section class="container-fluid m-5">
    <h5 class="text-center pb-3">Search Results</h5>
    <div class="row gap-5">
        <div class="col-md-8">
            <div class="card">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Username</th>
                            <th scope="col">Searches</th>
                            <th scope="col">Number of Searches</th>
                        </tr>
                    </thead>
                    <tbody>
                        <% @results.each do |result| %>
                            <tr>
                                <th scope="row">1</th>
                                <td> <%= result.username %></td>
                                <td>
                                    <% result.recent_searches.each do |user_search| %>
                                        <p class="flex flex-column"><%= user_search.title %></p>
                                    <% end %>
                                </td>
                                <td> <%= result.user_searches.count %> </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
                
        </div>
        <div class="card col-md-4" style="width: 15rem;">
            <h5 class="text-center text-dark m-3">Trending Articles</h5>
            <div class="card-body">
                <% @results.each do |trend| %>
                    <% trend.trending_articles.each do |trending, key| %>
                        <div class="d-flex gap-3">
                            <%= truncate(trending, :length => 12, :separator => ' ') %>
                            <p><%= key %> times</p>
                        </div>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
    
</section>

app/views/user_search/show.html.erb
<h1>UserSearch#show</h1>
<p>Find me in app/views/user_search/show.html.erb</p>